### ISSUE TITLE
Not working in AS on Mac

### ISSUE THREAD

**Issue by elroid** [alexzaitsev/android-styler#1]
Hi. Was really excited to try this plugin as it's solves something that's bugged for years! Unfortunately, it doesn't seem to be working with Android Studio (1.4.1) on my Mac (10.10.5). I've tried ctrl-shift-D as well as Cmd-shift-D but neither seems to do anything. I'm also not clear what is meant by "or context menu" since i can't see anything related to this plugin in the (right-click) menu.

**Comment by alirezaafkar** [comment]
Same problem with Android Studio 1.5.2 on Mac 10.11.1

**Comment by alexzaitsev** [comment]
Tried on Mac 10.10.5 and AS 1.5 Beta - everything works.
![default](https://cloud.githubusercontent.com/assets/2372414/10937324/d05d1198-82fa-11e5-9b69-b16c986f78de.png)

Did you copy some attributes from your View? Maybe you have nothing to paste.

**Comment by elroid** [comment]
<img width="394" alt="screen shot 2015-11-04 at 12 28 15" src="https://cloud.githubusercontent.com/assets/570665/10938159/e1ee1642-82ef-11e5-8f18-51920e8dd631.png">

Yeah, i'm not seeing that item in the menu either. Not sure why this could be, i checked that v1.0.1 of the plug in is enabled....

**Comment by alexzaitsev** [comment]
Hmm. You can try to delete installed plugin and install from jar: https://github.com/alexzaitsev/android-styler/releases/tag/1.0.1 
Maybe it will help

**Comment by elroid** [comment]
Uninstalled the repository version, restarted, installed from the jar, restarted. Same problem. :-(

**Comment by alexzaitsev** [comment]
Can't define the problem right now. I'll think about it.

**Comment by alexzaitsev** [comment]
Closed as obsolete
